---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpuexecutioncap: 50

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4
  - name: ubuntu-13.10
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[chef-dev-workstation::default]
    attributes:
      admin:
        username: 'vagrant'
        password: '$1$/cjpQf6u$i9lY6beWk/8bk.D9heAor0'

  - name: docker
    run_list:
      - recipe[chef-dev-workstation::default]
      - recipe[chef-dev-workstation::docker]
    attributes:
      admin:
        username: 'vagrant'
        password: '$1$/cjpQf6u$i9lY6beWk/8bk.D9heAor0'
