---
driver:
  name: docker
provisioner:
  name: chef_zero
driver_config:
  require_chef_omnibus: true
  socket: tcp://localhost:4243
platforms:
- name: centos-6.4
  driver_config:
    image: centos:6.4
    platform: centos
- name: ubuntu-12.04
  driver_config:
    image: ubuntu:12.04
    platform: ubuntu
- name: ubuntu-13.10
  driver_config:
    image: ubuntu:13.10
    platform: ubuntu
- name: ubuntu-prebuilt
  driver_config:
    image: scarolan/chef_ubuntu_workstation
    platform: ubuntu
suites:
  - name: chefuser
    run_list:
    - recipe[chef-dev-workstation::default]
    attributes:
      admin:
        username: 'chef'
        password: '$1$I/vRL6rk$uKtlDM/WKwSw3ShM7RITP/'
