---
driver:
  name: docker
provisioner:
  name: chef_zero
driver_config:
  require_chef_omnibus: true
platforms:
- name: centos-6.4
  driver_config:
    image: centos:6.4
    platform: rhel
- name: ubuntu-12.04
  driver_config:
    image: ubuntu:12.04
    platform: rhel
suites:
  - name: default
    run_list:
    - recipe[chef-dev-workstation::default]
    attributes:
      admin:
        username: 'kitchen'
        password: '$1$Bk.Woknd$/MgXOLE3PS3fPYAIuaDJE.'
