---
driver:
  name: docker
provisioner:
  name: chef_zero
driver_config:
  require_chef_omnibus: true
platforms:
- name: dind
  driver_config:
    image: jpetazzo/dind
    platform: ubuntu
    privileged: true
    provision_command: 
      - sed -i '/exec bash/d' /usr/local/bin/wrapdocker
      - /etc/init.d/apparmor teardown
    
suites:
  - name: vmception
    run_list:
    - recipe[chef-dev-workstation::default]
    attributes:
      admin:
        username: 'kitchen'
        password: '$1$Bk.Woknd$/MgXOLE3PS3fPYAIuaDJE.'
