---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4
  - name: opscode-ubuntu-13.04

suites:
  - name: default
    run_list:
      - recipe[chef-dev-workstation]
    attributes: {
      admin: {
        username: admin,
        password: '$1$2COvX4FL$mTFCyb8YRGTOtLMTcEkeG1',
        readme: 'The default password is simply "password".  Please change it.\nYou can run "openssl passwd -1 mypass" to generate a new encrypted password.'
      }
    }

