language: ruby
bundler_args: --without kitchen_vagrant
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - Gemfile
branches:
  only:
    - master
    - develop
script:
  - bundle exec rake style
  - bundle exec rake spec
